from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import json

import numpy as np


@dataclass(frozen=True)
class BenchmarkStates:
    mu: float
    initial: np.ndarray
    dro_seed: np.ndarray
    target: np.ndarray
    target_mode: str = "catalog_dro_phase"
    target_metadata: dict = field(default_factory=dict)
    teacher_controls: np.ndarray | None = None


def schedule_to_bitstring(schedule: np.ndarray) -> str:
    return "".join(str(int(v)) for v in np.asarray(schedule, dtype=int))


def teacher_control_schedule(
    *,
    n_segments: int,
    amax: float,
    teacher_cfg: dict | None = None,
) -> tuple[np.ndarray, dict]:
    """Deterministic norm-bounded cislunar teacher maneuver.

    The control law is intentionally simple and fully disclosed: it activates a
    fixed subset of windows and applies smooth sinusoidal direction changes in
    the rotating-frame axes. It is a benchmark generator, not an optimizer.
    """
    cfg = dict(teacher_cfg or {})
    if n_segments <= 0:
        raise ValueError("n_segments must be positive")
    if amax <= 0.0:
        raise ValueError("amax must be positive for teacher target generation")

    active_windows = cfg.get("active_windows")
    if active_windows is None:
        start = max(0, int(round(0.33 * n_segments)))
        main = list(range(start, min(n_segments, start + max(4, n_segments // 4))))
        reserve = [i for i in range(int(round(0.58 * n_segments)), n_segments, 2)]
        active_windows = sorted(set(main + reserve))
    active = np.zeros(n_segments, dtype=int)
    for idx in active_windows:
        i = int(idx)
        if i < 0 or i >= n_segments:
            raise ValueError(f"teacher active window {i} outside 0..{n_segments - 1}")
        active[i] = 1

    amplitude_fraction = float(cfg.get("amax_fraction", cfg.get("amplitude_fraction", 0.55)))
    if not (0.0 < amplitude_fraction <= 1.0):
        raise ValueError("teacher amax_fraction must be in (0, 1]")
    phase_offset = float(cfg.get("phase_offset", 0.35))
    out_of_plane_fraction = float(cfg.get("out_of_plane_fraction", 0.22))

    controls = np.zeros((n_segments, 3), dtype=float)
    active_idx = np.flatnonzero(active)
    for rank, i in enumerate(active_idx):
        tau = (i + 0.5) / float(n_segments)
        arc_tau = rank / max(1, active_idx.size - 1)
        taper = 0.82 + 0.18 * np.sin(np.pi * arc_tau)
        direction = np.array(
            [
                np.cos(2.0 * np.pi * tau + phase_offset),
                0.72 * np.sin(1.5 * np.pi * tau + 0.3),
                out_of_plane_fraction * np.sin(4.0 * np.pi * tau + 0.8),
            ],
            dtype=float,
        )
        direction /= max(float(np.linalg.norm(direction)), 1e-12)
        controls[i] = float(amax) * amplitude_fraction * taper * direction

    norms = np.linalg.norm(controls, axis=1)
    max_norm = float(np.max(norms)) if norms.size else 0.0
    if max_norm > float(amax) * (1.0 + 1e-12):
        controls *= float(amax) / max_norm
        norms = np.linalg.norm(controls, axis=1)

    metadata = {
        "control_law": "deterministic_sinusoidal_rotating_frame_v1",
        "description": "fixed active windows with smooth sinusoidal rotating-frame acceleration directions; target generated by forward CR3BP propagation from the JPL NRHO-like initial state",
        "active_windows_zero_based": active_idx.astype(int).tolist(),
        "active_windows_one_based": (active_idx + 1).astype(int).tolist(),
        "active_schedule": schedule_to_bitstring(active),
        "active_fraction": float(np.mean(active)),
        "amax_fraction": amplitude_fraction,
        "out_of_plane_fraction": out_of_plane_fraction,
        "phase_offset": phase_offset,
        "max_control_norm": float(np.max(norms)) if norms.size else 0.0,
        "seed": cfg.get("seed"),
    }
    return controls, metadata


def load_source_states(
    path: str | Path,
    transfer_time: float,
    substeps: int = 256,
    target_mode: str = "catalog_dro_phase",
    *,
    segments: int | None = None,
    amax: float | None = None,
    teacher: dict | None = None,
    phase_time: float | None = None,
) -> BenchmarkStates:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    mu = float(data["mu"])
    initial = np.asarray(data["states"]["initial_nrho_like_l2_southern_halo"]["state"], dtype=float)
    dro_seed = np.asarray(data["states"]["target_dro_seed"]["state"], dtype=float)
    mode = str(target_mode or "catalog_dro_phase")
    if mode == "catalog_dro_phase":
        target = propagate_ballistic(dro_seed, mu, transfer_time, substeps)
        metadata = {
            "target_mode": mode,
            "target_state_generation": "ballistic propagation of target_dro_seed for transfer_time",
            "generation_substeps": int(substeps),
        }
        return BenchmarkStates(mu=mu, initial=initial, dro_seed=dro_seed, target=target, target_mode=mode, target_metadata=metadata)
    if mode == "catalog_halo_phase_shift":
        if phase_time is None:
            raise ValueError("catalog_halo_phase_shift target generation requires benchmark.phase_time")
        target = propagate_ballistic(initial, mu, float(phase_time), substeps)
        metadata = {
            "target_mode": mode,
            "target_state_generation": "ballistic CR3BP phase propagation of initial_nrho_like_l2_southern_halo for benchmark.phase_time",
            "source_state": "initial_nrho_like_l2_southern_halo",
            "phase_time": float(phase_time),
            "transfer_time": float(transfer_time),
            "generation_substeps": int(substeps),
            "dynamic_model": "Earth-Moon CR3BP with zero thrust",
            "teacher_generated": False,
        }
        return BenchmarkStates(mu=mu, initial=initial, dro_seed=dro_seed, target=target, target_mode=mode, target_metadata=metadata)
    if mode == "teacher_controlled":
        if segments is None or amax is None:
            raise ValueError("teacher_controlled target generation requires segments and amax")
        controls, teacher_metadata = teacher_control_schedule(n_segments=int(segments), amax=float(amax), teacher_cfg=teacher)
        target, _ = propagate_controls_batch(initial, controls, mu, transfer_time, int(substeps))
        target_state = target[0]
        dt = float(transfer_time) / float(segments)
        metadata = {
            "target_mode": mode,
            "target_state_generation": "teacher-controlled propagation from initial_nrho_like_l2_southern_halo",
            "generation_substeps_per_segment": int(substeps),
            "teacher": {
                **teacher_metadata,
                "fuel": float(dt * np.sum(np.linalg.norm(controls, axis=1))),
                "target_state": target_state.astype(float).tolist(),
                "controls": controls.astype(float).tolist(),
            },
        }
        return BenchmarkStates(
            mu=mu,
            initial=initial,
            dro_seed=dro_seed,
            target=target_state,
            target_mode=mode,
            target_metadata=metadata,
            teacher_controls=controls,
        )
    raise ValueError(f"unknown benchmark target_mode: {mode}")


def cr3bp_derivative(states: np.ndarray, mu: float, accel: np.ndarray | None = None) -> np.ndarray:
    s = np.asarray(states, dtype=float)
    scalar = s.ndim == 1
    if scalar:
        s = s[None, :]

    x, y, z, vx, vy, vz = [s[:, i] for i in range(6)]
    r1 = np.sqrt((x + mu) ** 2 + y**2 + z**2)
    r2 = np.sqrt((x - 1.0 + mu) ** 2 + y**2 + z**2)
    r1 = np.maximum(r1, 1e-12)
    r2 = np.maximum(r2, 1e-12)

    ax = 2.0 * vy + x - (1.0 - mu) * (x + mu) / r1**3 - mu * (x - 1.0 + mu) / r2**3
    ay = -2.0 * vx + y - (1.0 - mu) * y / r1**3 - mu * y / r2**3
    az = -(1.0 - mu) * z / r1**3 - mu * z / r2**3

    if accel is not None:
        a = np.asarray(accel, dtype=float)
        if a.ndim == 1:
            a = a[None, :]
        ax = ax + a[:, 0]
        ay = ay + a[:, 1]
        az = az + a[:, 2]

    out = np.column_stack((vx, vy, vz, ax, ay, az))
    return out[0] if scalar else out


def rk4_step(states: np.ndarray, mu: float, dt: float, accel: np.ndarray | None = None) -> np.ndarray:
    k1 = cr3bp_derivative(states, mu, accel)
    k2 = cr3bp_derivative(states + 0.5 * dt * k1, mu, accel)
    k3 = cr3bp_derivative(states + 0.5 * dt * k2, mu, accel)
    k4 = cr3bp_derivative(states + dt * k3, mu, accel)
    return states + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)


def propagate_ballistic(state0: np.ndarray, mu: float, tf: float, substeps: int) -> np.ndarray:
    state = np.asarray(state0, dtype=float).copy()
    dt = tf / float(substeps)
    for _ in range(substeps):
        state = rk4_step(state, mu, dt)
    return state


def feedback_acceleration(
    states: np.ndarray,
    target: np.ndarray,
    active: np.ndarray,
    amax: float,
    kr: float,
    kv: float,
) -> np.ndarray:
    s = np.asarray(states, dtype=float)
    direction = kr * (target[:3] - s[:, :3]) + kv * (target[3:] - s[:, 3:])
    norm = np.linalg.norm(direction, axis=1, keepdims=True)
    unit = direction / np.maximum(norm, 1e-12)
    return unit * (amax * active[:, None])


def propagate_feedback_batch(
    state0: np.ndarray,
    schedules: np.ndarray,
    target: np.ndarray,
    mu: float,
    tf: float,
    amax: float,
    kr: float,
    kv: float,
    substeps_per_segment: int,
    return_history: bool = False,
) -> tuple[np.ndarray, np.ndarray | None]:
    schedules = np.asarray(schedules, dtype=float)
    if schedules.ndim == 1:
        schedules = schedules[None, :]
    m, n = schedules.shape
    states = np.repeat(np.asarray(state0, dtype=float)[None, :], m, axis=0)
    dt = tf / float(n * substeps_per_segment)
    history = [states.copy()] if return_history else None

    for i in range(n):
        active = schedules[:, i]
        for _ in range(substeps_per_segment):
            accel = feedback_acceleration(states, target, active, amax, kr, kv)
            states = rk4_step(states, mu, dt, accel)
            if return_history:
                history.append(states.copy())
    if return_history:
        return states, np.asarray(history)
    return states, None


def propagate_controls_batch(
    state0: np.ndarray,
    control_schedules: np.ndarray,
    mu: float,
    tf: float,
    substeps_per_segment: int,
    return_history: bool = False,
) -> tuple[np.ndarray, np.ndarray | None]:
    controls = np.asarray(control_schedules, dtype=float)
    if controls.ndim == 2:
        controls = controls[None, :, :]
    m, n, _ = controls.shape
    states = np.repeat(np.asarray(state0, dtype=float)[None, :], m, axis=0)
    dt = tf / float(n * substeps_per_segment)
    history = [states.copy()] if return_history else None
    for i in range(n):
        accel = controls[:, i, :]
        for _ in range(substeps_per_segment):
            states = rk4_step(states, mu, dt, accel)
            if return_history:
                history.append(states.copy())
    if return_history:
        return states, np.asarray(history)
    return states, None
